name = "zeroada"
description = "A minimalist Zola theme that prioritizes clean CSS and avoids heavy JavaScript. Enjoy a seamless user experience with lightning-fast load times. Let your content take center stage in a clutter-free, elegant design that enhances readability. Responsive and efficient, zeroada brings focus to your ideas."
license = "MIT"
homepage = "https://github.com/adaschevici/zeroada"
min_version = "0.5.0"
demo = "https://zeroada.pages.dev"

[extra]


[author]
name = "adaschevici"
homepage = "https://speyllsite.pages.dev/"
